language: php

php:
  - 7.0

before_script:
  - composer install --dev --no-interaction

script:
  - ./vendor/bin/kahlan --coverage=1 --clover=clover.xml

after_success:
  - if [ $(phpenv version-name) = '7.0' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) = '7.0' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi
