---

language: php

php:
  - 7.2

before_script:
  - mkdir -p build/logs/
  - composer install --dev --no-interaction --prefer-dist
  - composer require --dev --no-interaction --prefer-dist php-coveralls/php-coveralls

script:
  - php vendor/bin/kahlan --cc=true --coverage=4 --clover=build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v
