language: php

php:
  - 7.0

before_script:
  - composer install --dev --no-interaction --prefer-dist

script:
  - ./vendor/bin/kahlan --cc=true --coverage=4 --clover=clover.xml

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'
